### ISSUE TITLE
v2: Order Change

### ISSUE THREAD

**Issue by vallard** [CiscoUcs/KUBAM-Frontend#17]
The most important should probably go first.  I'd prefer it to be: 

Hosts
Networks
Images
Infrastructure
Settings 
Feedback

I think the hosts should go first cause those are the ones that we would look the most.  The one question I have is where the monitoring things should be that @janeuzil wrote.  Is there a way you drill down into one of the nodes and each node would have its own page?

**Comment by larabenito** [comment]
solved, changed the order
