### ISSUE TITLE
ISO image page

### ISSUE THREAD

**Issue by vallard** [CiscoUcs/KUBAM-Frontend#22]
page isn't consistent with hosts pages.  Make actions a dropdown box at the top with select button at the top to perform actions like delete or edit.

**Comment by vallard** [comment]
It still isn't consistent as the dropdown box is outside the white box, while the others are inside the white box.  Almost there though!  Also probably shouldn't say delete hosts on the ISO image stuff.

**Comment by 3191110276** [comment]
Done
