### ISSUE TITLE
Name in images should be nicer

### ISSUE THREAD

**Issue by 3191110276** [CiscoUcs/KUBAM-Frontend#35]
The Image mapping table shows the name of the OS in small letters, but it should be shown nicer with capital letters

**Comment by vallard** [comment]
Cool, you can certainly create a mapping that changes the name to something nice.  The other thing we can do is create a display-name variable that you can use.  How would that sound?

**Comment by 3191110276** [comment]
Display variable would work for us

**Comment by 3191110276** [comment]
Did it with a function now
