### ISSUE TITLE
Allow to dynamically change the IP for the request script

### ISSUE THREAD

**Issue by 3191110276** [CiscoUcs/KUBAM-Frontend#36]
IP needs to be changeable, even without an active connection to the KUBAM server

**Comment by 3191110276** [comment]
IP can be updated now, but port number cannot be updated yet. If we reload the browser, the IP will be gone though, so we need a function on the frontend server that allows us to set an IP that can be injected dynamically

**Comment by 3191110276** [comment]
Frontend part is done, need a script on the backend now which automatically updates the IP of the KUBAM server

**Comment by vallard** [comment]
finished this in commit today
